# Generated by Django 6.0.6 on 2026-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0002_infomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
